---
title: "Affidavit"
editor: visual

author:
    - name: Ingrid Anne Mercado
      email: mercado.ingrid@stud.hs-fresenius.de
      affiliations: Fresenius University of Applied Science
      corresponding: true

floatsintext: true
wordcount-banner: true
filters:
  - wordcount
  
format:
  apaquarto-pdf:
    documentmode: stu
    course: Data Science and Data Analytics  (WS 2025/26)
    professor: Prof. Dr. Stephan Huber
    duedate: '2026-02-19'
    keep-tex: false
    fig-align: "left"
    include-in-header:
      text: |
        \linespread{1.5}
        <!-- This equals 1.5 linespacing in Word -->
  apaquarto-html:
    toc: true
    embed-resources: true


a4paper: true


---

## Affidavit

I hereby affirm that this submitted paper was authored unaided and solely by me. Additionally, no
other sources than those in the reference list were used. Parts of this paper, including tables and
figures, that have been taken either verbatim or analogously from other works have in each case
been properly cited with regard to their origin and authorship. This paper either in parts or in its
entirety, be it in the same or similar form, has not been submitted to any other examination board
and has not been published.

I acknowledge that the university may use plagiarism detection software to check my thesis. I
agree to cooperate with any investigation of suspected plagiarism and to provide any additional
information or evidence requested by the university.

Checklist:

- [x] The handout contains 3-5 pages of text.
- [x] The submission contains the Quarto file of the handout.
- [x] The submission contains the Quarto file of the presentation.
- [x] The submission contains the HTML file of the handout.
- [x] The submission contains the HTML file of the presentation.
- [x] The submission contains the PDF file of the handout.
- [x] The submission contains the PDF file of the presentation.
- [x] The title page of the presentation and the handout contain personal details (name, email,
matriculation number).
- [x] The handout contains a bibliography, created using BibTeX with an APA citation style.
- [x] Either the handout or the presentation contains R code that proofs the expertise in coding.
- [x] The filled out Affidavit.
- [x] The link to the presentation and the handout published on GitHub.

Ingrid Anne Mercado, 03.12.2025, Köln, Germany
